#!/bin/sh

# bat=/sys/class/power_supply/BAT1/
bat="$(find /sys/class/power_supply -name "BAT*" | head -1)"
per="$(cat "$bat/capacity")"

icon () {
    [ $(cat "$bat/status") = Charging ] && echo "" && exit

    if [ "$per" -gt "90" ]; then
        icon=""
    elif [ "$per" -gt "80" ]; then
        icon=""
    elif [ "$per" -gt "70" ]; then
        icon=""
    elif [ "$per" -gt "60" ]; then
        icon=""
    elif [ "$per" -gt "50" ]; then
        icon=""
    elif [ "$per" -gt "40" ]; then
        icon=""
    elif [ "$per" -gt "30" ]; then
        icon=""
    elif [ "$per" -gt "20" ]; then
        icon=""
    elif [ "$per" -gt "10" ]; then
        icon=""
    elif [ "$per" -gt "0" ]; then
        icon=""
    else
            echo  && exit
    fi
    echo "$icon"
}
percent() {
    if [ $(cat "$bat/status") != Charging ]; then
        if [ "$per" -lt "3" ]; then 
            shutdown 0
        fi
        if [ "$per" -lt "10" ]; then 
            notify-send -t 10000 -u critical "Battery critical" "$per% $(icon)"
        fi
    fi

    echo $per "$(icon)"
}


percent

# [ $1 = Icon ] && icon
# [ $1 = Percent ] && percent
